language: node_js

env:
  global:

    # PAPERTRAIL_HOST
    - secure: "ynQecPEXmTYY+QdlVivS5eYuohsAMAwU7kB4/r6XTKsQTI2xFL9oa8mDJbCGxEEC/GYBERdDc9GE4mf56Y83fXtDJlU5lfIf0nwHCL3IyZyj+IPvHv9vvi8gFJed9uc+g1xxpcFqXWIs5Lt0qqQoFDCcgXwBkyNiPeKf3l8NLqxTXahJm71F9U/ogmbymTZfm8bbbbrjtxD7H6VkIZJMFTVFiwXlLgaQe75DT5YrAXRemzKOX2h4DC4A9PF+i6JXXR2uzoP63AuAhjZ2AjLkRZe885naf+3S/tKZGQYs6reI02N1K9oOXZvZZVCcaEztmnrLyLGY2Spk2/xG7IzjqStT/4ckdf/MGrNDPlkLv667bElzbMKcsK/u1pr78CVjq4UjLhO6A5pzsWVks4s4jPPW6qLvBuGf3P8vTNuXruSc5vkfHXbzM0SPSCeVyrTKWjxcMtDgc1CC5Ni48IAaOK6Epi+RHwN8zlJbROo2gCQly0FCIi064y3KmR4/t2TcUb/GU26kUkOXwPJga20RQf3p3S+1K1LIF0CHkIu0EjAxKRTxejLus4IuPSxyxRCw65ej381GGH3KG8c8FY3pLg6/+BVG3i9sgDfLnkeB4uPaPOx5c4XYxDGI7yic0Wa4dZqgFsZqJ2AQIdCA864XNTvHoDLPJuQpqXjrrwiWi0I="

    # PAPERTRAIL_PORT
    - secure: "OV8UQDIRbvKG0F6zu5t6PvNfw1SNs72bIj6jdUocqoZtjObxiU1YPaTsuweOKmGQRtdbsSQtEl4BVT36aYd0+7i1CA9BrO107n5k1YqOJwW/SktqTMAtYM7eNYU265zdn+1PaP4ImjNN230LOVxZIiuEPxsbRWpicvqqIDxWvOja2TmsV5ZbPHOHPcVGlSP3fOrZWLZUUozNQO75zoX7z2/QG/d7PmeSSaeCKCLqZAILL3YJTnXoGJ5+3ZzLiEJH3uKOFSJ74cttAj0kiwN9BeBRh/6DGGukSsZfxXw9l+0CcjoNvkEeyrw/WdmnLFtPz/LpfpCuAxyROeFqzM1Y6fEgSytEU3tf5ptpvrBkStj0dgh5z9Ru/HUSf0uSy4brJ5ue5YP96DF62TkwHEx3wuNDlJgcwYcfK34XAikg9h+9ydZwglPcD++zCdBUJcse22FMyp5WIFsX7WhVCFU8TSGBzZBiKhRuFUGKPjjJDnmNqKzMdU5STqCzL+KC3VeLJNJOYRNcH4SZDrOdmcO5iU5ifROfUJAfpoGNXr1A5lml5sRGeeQP27MAOZMlI5NEX5V32I7a1P6NvhZ08lHD00YrNJKrieyym79TiTNiQzM7VQpZ+gKxdCvBlxc4wEjh6kfgEmICRzzyAZUao5J2n5n0bqh8b479plcVjMtQVH8="

    # AWS_ACCESS_KEY_ID
    - secure: "xdSE4zBSF5eZ5DiVWzfU41lQKAEg95yRuelh9SDFooql4YhvBxgw1zWzoNdDktL1Mj0cSmUt/fnzxv/IhID9RmBoLGxNS7LY0Ipovpn/r+M2p4uy4SbdZBkVXJBF4dSuLKq+aZTCeTRWOUb3BTZ5gmjjRs4ZpxH53v+HtUuwwnq0y6KjoCGGGON2rlV7fDEVjLJOcaza9YDhKi7jVvCLDADvsoZf7o4tkjJYHz+hYjkPX+w3TY0xLmlrl+9jMtjXZWl9OLe3/Eu0YrvWTkxgyUi2Zmcv7KYtptuvQo+yHlpviKd+QjA9BSSHSas6/FWUs13hdjY6QTuE0w3G2LfGT9Ku3aVK6OXvKjNZKm3dept5qdouXepfO2XGA4GpQSu6YIWW5hSfAevQGAU+neavuZcB1NqoKeydSAOT8A95HZIRhzmVnreJawOWZn4bgHbP6vy0pEOF5NBTmFsXw5bINJ7U9ehbtVvY2TjJGC7AVvina3Y73ETAMlzAz2SdDc3HQ9BwLAhqLao8hsKct8VgdNK1Ez83/vb7Y5pHxoGLOJF5OfihAJToUBQwf73PA7mm74xjIRpGfNiW8HZW9wOBmcfOsp5VXQIWpIhzIBan60eDEHP1Yryb2bZT7BvovXObEs/d4T4r4O5ceLFoQexBfahq6E1+LRuQ1tvXl5nBejw="

    # AWS_SECRET_ACCESS_KEY
    - secure: "vpzqshWK9JI9wnop+Vd4HgygZE6H8WlVMIfT+K0XVZH7g5M4YOZOPgsxRg33bbUN9dkzkXuTuASHHN+eIpmjoaXOEQBtZEffI/B0uoAcPHMubJuNK0Zr2tJ3EU1XgKKxnl/wcGhQ0WV0qgpEAYfHeZYQP+DKfRqsDgr31U8SuBLw3Hzv5ah8PLsrO9tW0R+9nrBjKPXJixarlLd2wouMJ200W243q0EoY3Vu+Di+nORXthT+pQC4likBAUq5YwZhVZcuvPHnHaFmYcND+u+vdzAkiBiwkKGCMnH16InYlsz90/f3OHtEmWszVleqPsJOJZH10Y7wzOQG5I2zB8VoTRiKlryr46B2t4PA6HVVbyi5ZS2sbl0MQa6F28upnnSM3Q2/2CkfPZtbo1CxmF+l+49xNoCyieH/EV/dKjZEd5UMWXVzIZx3/FUAWL+v3gGw949ZbRQjipHTgOQdjlmmOJ9RglB0hsRQRruqOYKTwsp787cmQESjQZ7eVtweZiwU3i4ebRrI032AOBVUV4XZllUzYmsamTHyxGJ3ywwxUQjwTmCeU+AnCo+z6BhMuEM7c4jRGWHNbNqi/FgI+DZIYvhb8qDQ4srhpytlC0E37LxzpEz0H8LSzhgUkYAEjtudaOkQB7IINrDeGPHBKVDcnJJNqWPEAdD1c07TnrFKlx8="

    - LAMBDA_NAME=cloudwatchToPapertrail
    - AWS_DEFAULT_REGION=ap-southeast-2

cache:
  yarn: true
  directories:
    - node_modules

install:
  - echo 'Nothing to do'.

script:
  - yarn lint
  - make test

deploy:
  provider: script
  script: WAIT_FOR_FLUSH=true make deploy
  on:
    branch: master

notifications:
  email: false
  slack:
    rooms:
      - secure: "r9mNtdswpuUrtoqTmMAzK80V2ajUAoJFdDgjVE1/Hg8BBwtb9OyUjGBtvmo6reGblp0B3tTYYwziXl3MCGyvbEizUb9r38TIwfx/1W+6q2fBQszWrW5VjE2ykECCyN6PcpEPcX0IKMrLknNhOyeE7XW6W0fvZ2UnKh/8jZLTBCcveCrLj0ZHWctEAyDLlnnzTYn7koXlVYRHRVwqCeK2y7zwdJDp/0/aHllDrVyi2s6mcqwXqtU7D/uaO0kxR5PAcmHng8kM8esDb5CHg6qnQgzO6GPKARsp8JnyXvgOTQh6vVvPusQv2p6k3o29gfTkgq50eNzQXBja7rkdNoI4l1+jgsngZYe4doZAHxhXbqt5Siyv9ZILXt02OQY0vsfGih5qLO5yXrxuZ++89rbDBOWhQkLnqAWXpqc1yKa0r/BfSYp1eOwuKv9r2ppvdLo5EgquK3g+e2EgKaNhGDhSlBpJmo0/9m8dsM5Q75OUitt0H90EaJ6jf7rP7ow/23yHTH0kwWjBJb8igdRyJ68bYmk5XE3/7E29rQpOiGUq3btp6kfrAi9n8zCd0GzmISRNXg3AIJOiSC/8EgfLxENq+nwAb0Dco8zZJ1IKOhFbhlbpjz0VtI9qybUrUiWaq/OH5PNSBJgqP8bGXPzYlvoOi0IKJzRxDwmiGrJpn5vR6KA="
    on_start: always