language: node_js
services: docker
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAJODTOVVX6SQVT4PQ
    - AWS_DEFAULT_REGION=ap-southeast-2
    - LAMBDA_NAME=cloudwatchToPapertrail
    - LAMBDA_ALIAS=prod
    - PAPERTRAIL_HOST=logs5.papertrailapp.com

    # PAPERTRAIL_PORT
    - secure: OV8UQDIRbvKG0F6zu5t6PvNfw1SNs72bIj6jdUocqoZtjObxiU1YPaTsuweOKmGQRtdbsSQtEl4BVT36aYd0+7i1CA9BrO107n5k1YqOJwW/SktqTMAtYM7eNYU265zdn+1PaP4ImjNN230LOVxZIiuEPxsbRWpicvqqIDxWvOja2TmsV5ZbPHOHPcVGlSP3fOrZWLZUUozNQO75zoX7z2/QG/d7PmeSSaeCKCLqZAILL3YJTnXoGJ5+3ZzLiEJH3uKOFSJ74cttAj0kiwN9BeBRh/6DGGukSsZfxXw9l+0CcjoNvkEeyrw/WdmnLFtPz/LpfpCuAxyROeFqzM1Y6fEgSytEU3tf5ptpvrBkStj0dgh5z9Ru/HUSf0uSy4brJ5ue5YP96DF62TkwHEx3wuNDlJgcwYcfK34XAikg9h+9ydZwglPcD++zCdBUJcse22FMyp5WIFsX7WhVCFU8TSGBzZBiKhRuFUGKPjjJDnmNqKzMdU5STqCzL+KC3VeLJNJOYRNcH4SZDrOdmcO5iU5ifROfUJAfpoGNXr1A5lml5sRGeeQP27MAOZMlI5NEX5V32I7a1P6NvhZ08lHD00YrNJKrieyym79TiTNiQzM7VQpZ+gKxdCvBlxc4wEjh6kfgEmICRzzyAZUao5J2n5n0bqh8b479plcVjMtQVH8=

    # AWS_SECRET_ACCESS_KEY
    - secure: vpzqshWK9JI9wnop+Vd4HgygZE6H8WlVMIfT+K0XVZH7g5M4YOZOPgsxRg33bbUN9dkzkXuTuASHHN+eIpmjoaXOEQBtZEffI/B0uoAcPHMubJuNK0Zr2tJ3EU1XgKKxnl/wcGhQ0WV0qgpEAYfHeZYQP+DKfRqsDgr31U8SuBLw3Hzv5ah8PLsrO9tW0R+9nrBjKPXJixarlLd2wouMJ200W243q0EoY3Vu+Di+nORXthT+pQC4likBAUq5YwZhVZcuvPHnHaFmYcND+u+vdzAkiBiwkKGCMnH16InYlsz90/f3OHtEmWszVleqPsJOJZH10Y7wzOQG5I2zB8VoTRiKlryr46B2t4PA6HVVbyi5ZS2sbl0MQa6F28upnnSM3Q2/2CkfPZtbo1CxmF+l+49xNoCyieH/EV/dKjZEd5UMWXVzIZx3/FUAWL+v3gGw949ZbRQjipHTgOQdjlmmOJ9RglB0hsRQRruqOYKTwsp787cmQESjQZ7eVtweZiwU3i4ebRrI032AOBVUV4XZllUzYmsamTHyxGJ3ywwxUQjwTmCeU+AnCo+z6BhMuEM7c4jRGWHNbNqi/FgI+DZIYvhb8qDQ4srhpytlC0E37LxzpEz0H8LSzhgUkYAEjtudaOkQB7IINrDeGPHBKVDcnJJNqWPEAdD1c07TnrFKlx8=

cache:
  yarn: true
  directories:
    - node_modules

install: yarn
script: yarn lint && yarn test
before_deploy: rm -rf *rc.js

deploy:

  - provider: script
    script: pip install awscli --upgrade --user && make deploy
    skip_cleanup: true
    on:
      branch: master

  - provider: npm
    email: tdmalone@gmail.com
    api_key:
      secure: LxVonB8yniFcfQptIX9vqsnf+Fn9Fszp8s/6V8DkjFByKqngzJ7D1zA35Hpu8ChjUoUqrvi6W8KC8aWDS/Gmik8lt8ma1m1CxJjcvEB3J7HK83yUVAmnRUKsGIfR84nF3rOb5DzlI3Hf+yze6upcZcHGdaM5wFZhXMLBGlWsJGoGnAgapt1aKGi7xJ+1p7/TYq77GM97TfanpW5WyEGbSzEo2/bVaPdt/SCi1BNnpbqHI4+WUlNJ762Qv+B6TOYPseDxOy0TYB1MijRAeP4D+7Hp9I35LMi2lGScXTIFai1zdJu5fCOli8uLFc1crItgPgiQdlWl6Zc+Ri5belIBDH/xH2U6CK3pyxjeNf7WfYdROzcKMIEBBUvkP/sgB1gZckTjuwEd30TbQp7Sq9x17tMJowW4JtiKURwisyRPw7gK1xPsI6GCFGkj8oqGTmFL/uhznZKiLDj7GhCvB7CHgiZW1lIzsADD37Kn6ENSpdFcdP2TZrB5ONtz24Nf2qIKd8aG3ULm04gXGl18i5s9Zyyga9Oq1iigdW9KgwXDJXr0tWLT1w1BILkiyp9iOBDDkHvx/Td2gL6MjYhHWE3ntTaJ9u50WPN0vUE4IKSzWJNiy37IA+QxLnDGCviv9EQrNvdfNdsA43EUz8959GMUS1Nwd6jP7PtPteWrYAL69Xw=
    skip_cleanup: true
    on:
      branch: master
      tags: true

notifications:
  email: false
  slack:
    on_start: always
    rooms:
      - secure: r9mNtdswpuUrtoqTmMAzK80V2ajUAoJFdDgjVE1/Hg8BBwtb9OyUjGBtvmo6reGblp0B3tTYYwziXl3MCGyvbEizUb9r38TIwfx/1W+6q2fBQszWrW5VjE2ykECCyN6PcpEPcX0IKMrLknNhOyeE7XW6W0fvZ2UnKh/8jZLTBCcveCrLj0ZHWctEAyDLlnnzTYn7koXlVYRHRVwqCeK2y7zwdJDp/0/aHllDrVyi2s6mcqwXqtU7D/uaO0kxR5PAcmHng8kM8esDb5CHg6qnQgzO6GPKARsp8JnyXvgOTQh6vVvPusQv2p6k3o29gfTkgq50eNzQXBja7rkdNoI4l1+jgsngZYe4doZAHxhXbqt5Siyv9ZILXt02OQY0vsfGih5qLO5yXrxuZ++89rbDBOWhQkLnqAWXpqc1yKa0r/BfSYp1eOwuKv9r2ppvdLo5EgquK3g+e2EgKaNhGDhSlBpJmo0/9m8dsM5Q75OUitt0H90EaJ6jf7rP7ow/23yHTH0kwWjBJb8igdRyJ68bYmk5XE3/7E29rQpOiGUq3btp6kfrAi9n8zCd0GzmISRNXg3AIJOiSC/8EgfLxENq+nwAb0Dco8zZJ1IKOhFbhlbpjz0VtI9qybUrUiWaq/OH5PNSBJgqP8bGXPzYlvoOi0IKJzRxDwmiGrJpn5vR6KA=
